#----------------------------------------------------------------------
# This file was generated by img2py.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

annotation_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAATUlE"
    "QVQokWP8//8/AymAiSTV9NfAyIiJGgnY4LaYgaEBiSTopF13GdyUESRhDciq3ZQHxAZG5Jhm"
    "ZGRgYEAPlv//63FqIAYM9qRBDAAAZUwkX6kPg8sAAAAASUVORK5CYII=")
getannotation_iconData = annotation_icon.GetData
getannotation_iconImage = annotation_icon.GetImage
getannotation_iconBitmap = annotation_icon.GetBitmap

#----------------------------------------------------------------------
blue_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGZJ"
    "REFUOI3dk0sKACEMQ5PW+594hroSxEb8MKt5y5iEFixpjpF4nxg1emEyAmBfoIKrIjsJK58p"
    "cdXU+y09ApDLTiAitkaXYS9ME5zyh4LZD1vRct+scDpF7zcl7oaB4Zga19d4QwVOsSFLRqlm"
    "tAAAAABJRU5ErkJggg==")
getblue_iconData = blue_icon.GetData
getblue_iconImage = blue_icon.GetImage
getblue_iconBitmap = blue_icon.GetBitmap

#----------------------------------------------------------------------
compile_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAA3NCSVQICAjb4U/gAAAAjElE"
    "QVQYlYWP0Q3DIAxEH1E3Mv/pNLAGGcPM0QEYIJ6p/cAJRRXqCSGDnnx3obXGPz2AfX/CuSKO"
    "47UBTlQjxHGqQRybnMgZVZKMJ0oC2BzKGXCiD6r+OaBfJeF9fttFA0CuELPKcpMFLDDbqQBW"
    "PZMPKlM7SWYI2cyzGiqSbII61wvfhvcVSinLgpc+Sigs3pf6nTgAAAAASUVORK5CYII=")
getcompile_iconData = compile_icon.GetData
getcompile_iconImage = compile_icon.GetImage
getcompile_iconBitmap = compile_icon.GetBitmap

#----------------------------------------------------------------------
ext_method_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAATUlE"
    "QVQokWP8//8/AymAiSTVFGpgZGRgZMSiBFUcwwY0PRhGYHMSXBE2CzE0QAIN7gyMMMRmA1wR"
    "thAnOZRYsAvjjk3aRxzjoE5LxAEA+hQQJV9Qze4AAAAASUVORK5CYII=")
getext_method_iconData = ext_method_icon.GetData
getext_method_iconImage = ext_method_icon.GetImage
getext_method_iconBitmap = ext_method_icon.GetBitmap

#----------------------------------------------------------------------
gray_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHBJ"
    "REFUOI3dk8sNwCAMQ510sSzW8luMzdoTEgqpCKinvqOJLUciRHxAE67z1lrKhYZBANQHWMZZ"
    "EK+YrTm2RBFxh7B+FBHUWj1lAAAUY3RVt0i50NBglT8EvP2wGc33zQqrLfp5tkSvGVDH1Ni+"
    "xh0edrMnCONoN4sAAAAASUVORK5CYII=")
getgray_iconData = gray_icon.GetData
getgray_iconImage = gray_icon.GetImage
getgray_iconBitmap = gray_icon.GetBitmap

#----------------------------------------------------------------------
green_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGVJ"
    "REFUOI3dk8EOwCAIQ1v4/0827GRCgKmYnfaO2FZIgBRFxMawWKMqkxAAfUBl3AVJx1zppCoa"
    "1lleL+kRBqIct4Tb71ZmVaYOuvwh4G3DdkzfNyN0u/B6qYqnZiAc0+T6Gm94ALqGIkjrAWwi"
    "AAAAAElFTkSuQmCC")
getgreen_iconData = green_icon.GetData
getgreen_iconImage = green_icon.GetImage
getgreen_iconBitmap = green_icon.GetBitmap

#----------------------------------------------------------------------
keyword_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAU0lE"
    "QVQokWP8//8/AymAiSTVdNHAgsx54OCAJn2AgSHhwAG8NigwKDggSMJOUlBgePAAQRLWgKz6"
    "wYMBsYEFjX/gAQMDRB021QwMDIzDIGmQrAEAWNMinUe5XaAAAAAASUVORK5CYII=")
getkeyword_iconData = keyword_icon.GetData
getkeyword_iconImage = keyword_icon.GetImage
getkeyword_iconBitmap = keyword_icon.GetBitmap

#----------------------------------------------------------------------
loc_method_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAABNUlE"
    "QVQoka2SIVACQRSGfxzDo+01XnPj2tYG8SI0aNgkSpOmEZs0K1EbROKS1AbNuraj3bZ9DYMc"
    "w93cjOOMf9u3/7f7/t3X2O/3+IvOaqsCEUjt1nllvfRutp1H+XHTtRnc2f6poXHa0tg9+uCs"
    "8k06VHzQROlzel/T0tjNgMXI2IGZKrBq6q6etrmlaNFbTapAJmEb3pmC4dTykBNrVGp5yEo3"
    "EYL4TEIJWPvNBYUicWjr0RXfHHMTdkvvSqFzBEF+ACQmpAFCASiK1ZaM0iJ8OI+Swl1kB2tq"
    "lW5I2Y6FOkAefR7nhY+y4HMhH1RXd0oAgM/h4vK1F2V2fFMAUbDamQc7OlZK/+Cy7WT9xLRj"
    "ygBE8Je03vovOFGjMksCcX6z8h9E0Im5NV2UVQV+Vf3w/SfwDUpBgb9I2OI+AAAAAElFTkSu"
    "QmCC")
getloc_method_iconData = loc_method_icon.GetData
getloc_method_iconImage = loc_method_icon.GetImage
getloc_method_iconBitmap = loc_method_icon.GetBitmap

#----------------------------------------------------------------------
loc_var_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAZ0lE"
    "QVQokWP8//8/AymAiSTVdNHAgink0OAAZx9oOEBAg0ODQ4KDAoKb4HBgAYoeJjyqGRgYHBwU"
    "HBIccGogBlBVw4MHWAQZ0WLaIcHBAckbBw48QPM0ugaIHoQGVNXYNeAHgzAtAQC3+CHV+b8p"
    "lQAAAABJRU5ErkJggg==")
getloc_var_iconData = loc_var_icon.GetData
getloc_var_iconImage = loc_var_icon.GetImage
getloc_var_iconBitmap = loc_var_icon.GetBitmap

#----------------------------------------------------------------------
none_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAGUlE"
    "QVQokWP8//8/AymAiSTVoxpGNQwpDQBVbQMd5EZaEgAAAABJRU5ErkJggg==")
getnone_iconData = none_icon.GetData
getnone_iconImage = none_icon.GetImage
getnone_iconBitmap = none_icon.GetBitmap

#----------------------------------------------------------------------
orange_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAHVJ"
    "REFUOI3dk1EKgCAQRGen0wV1CcFTRV3CD2+X/RSIbrhKX83nOm+YBVeEE0qd25zKGX2UyghA"
    "8gANbAWxB9Z8VGEXzCGsXl0AjtVSBgAgaV9M1TXRR6kb9Ib8IODthzXBm/tmhd4WuZ/a0AoD"
    "xTE9Gr7GEV3DQCWNSu7czQAAAABJRU5ErkJggg==")
getorange_iconData = orange_icon.GetData
getorange_iconImage = orange_icon.GetImage
getorange_iconBitmap = orange_icon.GetBitmap

#----------------------------------------------------------------------
program_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAA3NCSVQICAjb4U/gAAAAjElE"
    "QVQYlYWQsQ0DIRAEd226cPI9fB1uw23AlUInXP59uAHn6+AFHNLLHhGxq7kDttbwD0IQ9KNh"
    "ZjcABN3dzBgwM3efphNBJIdA0mLq9dk4s2FKy3xhNHPO4/qOJ/Du5xFeRJLcts3dp0m74sTV"
    "9AKA9mm11vhn0QQcUGdZr1NKSdoVA1yRzOwyiHwBdDpKRPHumf8AAAAASUVORK5CYII=")
getprogram_iconData = program_icon.GetData
getprogram_iconImage = program_icon.GetImage
getprogram_iconBitmap = program_icon.GetBitmap

#----------------------------------------------------------------------
pulse_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAADxJ"
    "REFUOI1j/P///38GCgATJZoHhwEs2AQZGbErxhZaWA3AphiXoQMfBqMGIEUjrmhCBshqYNHM"
    "OPQzEwAvyA4ffyrwBAAAAABJRU5ErkJggg==")
getpulse_iconData = pulse_icon.GetData
getpulse_iconImage = pulse_icon.GetImage
getpulse_iconBitmap = pulse_icon.GetBitmap

#----------------------------------------------------------------------
red_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGhJ"
    "REFUOI3dk80OgDAMgoG+/yO7ejAmy4buJ57k2PERmqykAq1KObKdScHOCIB1gANHQVqBnU8W"
    "zves2q/uNROgXdeKCUxVd5KCfYPVkB8EPP2wMXhx36yw2qL2yw1nYaA5plvb17ijE7mJIki4"
    "MOGyAAAAAElFTkSuQmCC")
getred_iconData = red_icon.GetData
getred_iconImage = red_icon.GetImage
getred_iconBitmap = red_icon.GetBitmap

#----------------------------------------------------------------------
rg_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAF0lE"
    "QVQokWP8z0AaYCJR/aiGUQ1DSAMAQC4BH5CRCM8AAAAASUVORK5CYII=")
getrg_iconData = rg_icon.GetData
getrg_iconImage = rg_icon.GetImage
getrg_iconBitmap = rg_icon.GetBitmap

#----------------------------------------------------------------------
run_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAA3NCSVQICAjb4U/gAAAAcUlE"
    "QVQYlYWPyxGAIAxEnw5HG6AOcrcb2zD2RAE0YB204QEYf3z2kMkkb3aTKYTASAZY1qVD+MPP"
    "QxvghuSUVFNTh576cM24J2cAQQA84gRfNhZBcCj6c7KlRnCtuFiIvXPTj8g3ZaXFVnliUtXK"
    "+K0LWp0WW6LtEIEAAAAASUVORK5CYII=")
getrun_iconData = run_icon.GetData
getrun_iconImage = run_icon.GetImage
getrun_iconBitmap = run_icon.GetBitmap

#----------------------------------------------------------------------
run_unit_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAA3NCSVQICAjb4U/gAAAAc0lE"
    "QVQYlYXOQQ2AMAyF4R+yIwpmYwLmBnQggwlAAQKegQpAATY4QEhJYHuHpocvfe0k0UoAct4r"
    "Yp6PvnkGcKiUe17LN/J5u/865wJgZoAVS8msmHNTWkaItcfTMjbqHvGLvAA6ScOwVkq3LQZJ"
    "ECsIOAEaSCBgNNXDIwAAAABJRU5ErkJggg==")
getrun_unit_iconData = run_unit_icon.GetData
getrun_unit_iconImage = run_unit_icon.GetImage
getrun_unit_iconBitmap = run_unit_icon.GetBitmap

#----------------------------------------------------------------------
stop_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMCAIAAADZF8uwAAAAA3NCSVQICAjb4U/gAAAAfklE"
    "QVQYlYWPUQ2AMAxE3wiOKgAD84EMOhn4mIAZQMAUIAM+toVCgPVjaW7Xe61LKdGrEZhy/nGE"
    "fR+6MTWpTsyz/fAg61r6W9JyHEtzRKPfcc4FACL4J66BgmFFkKKrjgAiANvmW0ZNKrrFPRx2"
    "p+s6kTpo37fFP8qpatd0AnKLHdQn+4OtAAAAAElFTkSuQmCC")
getstop_iconData = stop_icon.GetData
getstop_iconImage = stop_icon.GetImage
getstop_iconBitmap = stop_icon.GetBitmap

#----------------------------------------------------------------------
volatile_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAA3NCSVQICAjb4U/gAAAAW0lE"
    "QVQokWP8//8/AymAiSTVdNHAgim0h5ERznbB9OF/VLCbgeE/EmrAUMCAR/V/BoZ1GHoGNpTW"
    "YxNkRIvpRkZGPSTuJQaGelQF6BogeuDsegxZLBrwg0GYlgB7XFijZzDRCgAAAABJRU5ErkJg"
    "gg==")
getvolatile_iconData = volatile_icon.GetData
getvolatile_iconImage = volatile_icon.GetImage
getvolatile_iconBitmap = volatile_icon.GetBitmap

#----------------------------------------------------------------------
yellow_icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABHNCSVQICAgIfAhkiAAAAGdJ"
    "REFUOI3dk8EOgDAIQ0v5/0+eeNGEsLq5xZM9sr4OEjCjo+poLWqN7tYZAVgOUOAsiCuw8lHD"
    "46zsZ/8cAOS4UhYx+W4gupvoYDHkBwFPGzYFL+6bEVa7yH6q4lsYKMd0a/sad3QCTLchSxnd"
    "e60AAAAASUVORK5CYII=")
getyellow_iconData = yellow_icon.GetData
getyellow_iconImage = yellow_icon.GetImage
getyellow_iconBitmap = yellow_icon.GetBitmap

