
all: ide debugger pk2cmd

ide:
	cd Jaluino && python2.5 setup.py bdist_egg --dist-dir=../
	cd Jaluino && python2.6 setup.py bdist_egg --dist-dir=../

debugger:
	cd JaluinoDebugger && python2.5 setup.py bdist_egg --dist-dir=../
	cd JaluinoDebugger && python2.6 setup.py bdist_egg --dist-dir=../
	
pk2cmd:
	cd jpk2cmd && python2.5 setup.py bdist_egg --dist-dir=../
	cd jpk2cmd && python2.6 setup.py bdist_egg --dist-dir=../
