
all: ide debugger

ide:
	cd Jaluino && python2.5 setup.py bdist_egg --dist-dir=../
	cd Jaluino && python2.6 setup.py bdist_egg --dist-dir=../

debugger:
	cd JaluinoDebugger && python2.5 setup.py bdist_egg --dist-dir=../
	cd JaluinoDebugger && python2.6 setup.py bdist_egg --dist-dir=../
	
