
all: ide debugger codetpl

ide:
	cd Jaluino && python2.5 setup.py bdist_egg --dist-dir=../
	cd Jaluino && python2.6 setup.py bdist_egg --dist-dir=../

debugger:
	cd JaluinoDebugger && python2.5 setup.py bdist_egg --dist-dir=../
	cd JaluinoDebugger && python2.6 setup.py bdist_egg --dist-dir=../
	
codetpl:
	cd codetemplater && python2.5 setup.py bdist_egg --dist-dir=../
	cd codetemplater && python2.6 setup.py bdist_egg --dist-dir=../
